services:

  proxy:
    image: nginx:alpine
    container_name: pj_proxy
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - mfe-host
      - mfe-program
      - mfe-syllabi
      - mfe-assignements
      - files

  api:
    build:
      context: .
      dockerfile: Shogun.Service.Api/Dockerfile
    container_name: pj_syllabi_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      MONGODB__CONNECTIONSTRING: "mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-haslo123}@host.docker.internal:27017/?authSource=admin"
      MONGODB__DATABASENAME: "${MONGO_DB:-pj_sylabi}"

  mfe-host:
    build:
      context: ../frontend/pj-studies-host
      dockerfile: Dockerfile
    container_name: pj_mfe_host
    restart: unless-stopped

  mfe-program:
    build:
      context: ../frontend/pj-studies-program
      dockerfile: Dockerfile
    container_name: pj_mfe_program
    restart: unless-stopped

  mfe-syllabi:
    build:
      context: ../frontend/pj-studies-syllabi
      dockerfile: Dockerfile
    container_name: pj_mfe_syllabi
    restart: unless-stopped

  mfe-assignements:
    build:
      context: ../frontend/pj-studies-assignements
      dockerfile: Dockerfile
    container_name: pj_mfe_assignements
    restart: unless-stopped

  files:
    image: nginx:alpine
    container_name: pj_files
    restart: unless-stopped
    volumes:
      - ./files:/usr/share/nginx/html:ro

volumes:
  mongo_data:
