services:

  api:
    build:
      context: .
      dockerfile: Shogun.Service.Api/Dockerfile
    container_name: pj_syllabi_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      MONGODB__CONNECTIONSTRING: "mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-haslo123}@host.docker.internal:27017/?authSource=admin"
      MONGODB__DATABASENAME: "${MONGO_DB:-pj_sylabi}"
    ports:
      - "${API_PORT:-8080}:8080"

  mfe-host:
    build:
      context: ../frontend/pj-studies-host
      dockerfile: Dockerfile
    container_name: pj_mfe_host
    restart: unless-stopped
    ports:
      - "4200:80"

  mfe-program:
    build:
      context: ../frontend/pj-studies-program
      dockerfile: Dockerfile
    container_name: pj_mfe_program
    restart: unless-stopped
    ports:
      - "4201:80"

  mfe-syllabi:
    build:
      context: ../frontend/pj-studies-syllabi
      dockerfile: Dockerfile
    container_name: pj_mfe_syllabi
    restart: unless-stopped
    ports:
      - "4202:80"

  mfe-assignements:
    build:
      context: ../frontend/pj-studies-assignements
      dockerfile: Dockerfile
    container_name: pj_mfe_assignements
    restart: unless-stopped
    ports:
      - "4203:80"

volumes:
  mongo_data:
