const { withNativeFederation, shareAll } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  name: 'shell',
  remotes: {
    'mfe-program':      'http://localhost:4201',
    'mfe-syllabi':      'http://localhost:4202',
    'mfe-assignements': 'http://localhost:4203',
    'mfe-users':        'http://localhost:4204',
    'mfe-lecturers-assignments': 'http://localhost:4205',
    'mfe-schedule':              'http://localhost:4206',
    'mfe-lecturer-schedule':     'http://localhost:4207',
  },
  shared: {
    ...shareAll({
      singleton: true,
      strictVersion: true,
      requiredVersion: 'auto',
      includeSecondaries: { skip: ['primeng', '@primeuix', 'primeicons'] },
    }),
  },
  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    'chart.js/auto',
    '@angular/cdk/drag-drop',
    '@angular/common/upgrade',
    '@angular/router/upgrade',
    '@angular/upgrade/static',
    'primeng',
    'primeng/',
    'primeicons',
    'primeicons/',
    '@primeuix/',
    '@primeuix/themes',
    '@primeuix/themes/tokens',
    '@primeuix/styled',
    '@primeuix/styles',
    '@primeuix/utils',
    '@primeuix/motion',
    'keycloak-js',
  ],
});
