import { Component, inject, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { ScheduleNote, ScheduleNotesService } from '../../services/schedule-notes.service';
import { MentionInputComponent, MentionRecipient } from '../mention-input/mention-input.component';

@Component({
  selector: 'app-plan-notes-drawer', imports: [FormsModule, ButtonModule, MentionInputComponent],
  template: `<div class="backdrop" (click)="closed.emit()"></div><aside><header><div><small>Plan zajęć</small><h3>Notatki planistów</h3></div><button class="close" (click)="closed.emit()"><i class="pi pi-times"></i></button></header><main>@for(note of service.notes(); track note.id){<details class="note"><summary><span>{{heading(note)}}</span><small>{{note.authorDisplayName}} · {{format(note.createdAt)}}</small></summary><article>@if(editingId()===note.id){<input [(ngModel)]="editTitle" maxlength="200" placeholder="Tytuł (opcjonalnie)"/><app-mention-input [value]="editDraft" (valueChange)="editDraft=$event" [recipients]="editRecipients" (recipientsChange)="editRecipients=$event" placeholder="Edytuj notatkę"/><p-button label="Zapisz" size="small" (onClick)="saveEdit(note)"/>} @else {<p>@for(part of bodyParts(note);track $index){@if(part.mention){<mark>{{part.text}}</mark>}@else {{{part.text}}}}</p>@if(note.recipients.length){<details class="saved-recipients"><summary><span class="pi pi-envelope"></span> Odbiorcy <b>{{note.recipients.length}}</b></summary><div class="saved-recipient-chips">@for(recipient of note.recipients; track recipient.userId){<span>{{recipient.displayName}}@if(recipient.email){ · {{recipient.email}}}</span>}</div></details>}<div class="actions">@if(note.canEdit){<button (click)="startEdit(note)">Edytuj</button>}@if(note.canDelete){<button (click)="remove(note)">Usuń</button>}</div>}</article></details>}@empty{<div class="empty">Brak notatek do planu.</div>}</main><footer><input [(ngModel)]="title" maxlength="200" placeholder="Tytuł (opcjonalnie)"/><app-mention-input [value]="draft" (valueChange)="draft=$event" [recipients]="recipients" (recipientsChange)="recipients=$event" placeholder="Napisz notatkę… Użyj @, aby wskazać odbiorcę"/><p-button label="Dodaj notatkę" icon="pi pi-plus" [disabled]="!draft.trim()" (onClick)="add()"/></footer></aside>`,
  styles: [`:host{position:fixed;inset:0;z-index:100}.backdrop{position:absolute;inset:0;background:#0f172a55}aside{position:absolute;top:0;right:0;display:flex;flex-direction:column;width:min(440px,96vw);height:100%;background:white;box-shadow:-10px 0 30px #0f172a33}header{display:flex;justify-content:space-between;padding:1rem 1.2rem;border-bottom:1px solid var(--p-surface-200)}h3{margin:.2rem 0}.close{border:0;background:transparent;cursor:pointer}main{flex:1;overflow:auto;padding:.7rem 1.2rem}.note{margin-bottom:.55rem;border:1px solid var(--p-surface-200);border-radius:7px;overflow:hidden}.note>summary{display:flex;flex-direction:column;gap:.15rem;padding:.7rem .8rem;background:var(--p-surface-50);cursor:pointer}.note>summary span{font-weight:600}.note>summary small{color:var(--p-surface-500)}article{padding:.8rem}article p{white-space:pre-wrap}mark{padding:.08rem .3rem;border-radius:4px;color:#3730a3;background:#e0e7ff;font-weight:650}.saved-recipients{margin:.4rem 0;border:1px solid #dbeafe;border-radius:7px;background:#f8fafc}.saved-recipients summary{padding:.4rem .55rem;color:#475569;font-size:.72rem;cursor:pointer}.saved-recipients summary b{padding:.08rem .35rem;border-radius:99px;color:#1e3a8a;background:#dbeafe}.saved-recipient-chips{display:flex;flex-wrap:wrap;gap:.35rem;padding:0 .55rem .55rem}.saved-recipient-chips span{padding:.25rem .5rem;border-radius:99px;color:#1e3a8a;background:#dbeafe;font-size:.72rem}.actions{display:flex;justify-content:flex-end;gap:.6rem}.actions button{border:0;color:var(--p-primary-700);background:transparent;cursor:pointer}footer{padding:1rem 1.2rem;border-top:1px solid var(--p-surface-200)}textarea,input{box-sizing:border-box;width:100%;margin-bottom:.5rem;padding:.6rem;border:1px solid var(--p-surface-300);border-radius:6px}textarea{resize:vertical}.empty{padding:3rem 0;text-align:center;color:var(--p-surface-500)}`],
})
export class PlanNotesDrawerComponent {
  readonly scheduleId = input.required<string>(); readonly closed = output<void>(); readonly service = inject(ScheduleNotesService);
  protected draft=''; protected title=''; protected editDraft=''; protected editTitle=''; protected recipients:MentionRecipient[]=[]; protected editRecipients:MentionRecipient[]=[]; protected readonly editingId=signal<string|null>(null);
  protected async add(){const body=this.draft.trim();if(!body)return;await this.service.add(this.scheduleId(),body,this.title.trim(),this.recipients.map(x=>x.userId));this.draft='';this.title='';this.recipients=[];}
  protected startEdit(note:ScheduleNote){this.editingId.set(note.id);this.editDraft=note.body;this.editTitle=note.title??'';this.editRecipients=note.recipients;}
  protected async saveEdit(note:ScheduleNote){if(this.editDraft.trim())await this.service.edit(note.id,this.editDraft.trim(),this.editTitle.trim(),this.editRecipients.map(x=>x.userId));this.editingId.set(null);}
  protected async remove(note:ScheduleNote){if(confirm('Usunąć notatkę?'))await this.service.remove(note.id);}
  protected format(value:string){return new Date(value).toLocaleString('pl-PL');}
  protected heading(note:ScheduleNote){return note.title?.trim()||`${note.body.slice(0,55)}${note.body.length>55?'…':''}`;}
  protected bodyParts(note:ScheduleNote){const tokens=note.recipients.map(x=>`@${x.displayName}`).sort((a,b)=>b.length-a.length);if(!tokens.length)return[{text:note.body,mention:false}];const set=new Set(tokens);const regex=new RegExp(`(${tokens.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')})`,'g');return note.body.split(regex).filter(Boolean).map(text=>({text,mention:set.has(text)}));}
}
