// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shogun.Schedule.Infrastructure;

#nullable disable

namespace Shogun.Schedule.Infrastructure.Migrations
{
    [DbContext(typeof(ScheduleDbContext))]
    [Migration("20260810201902_AddKeycloakUserIdentity")]
    partial class AddKeycloakUserIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "class_type", new[] { "lecture", "exercises", "laboratory", "project", "seminar", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "schedule_status", new[] { "draft", "published" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "study_mode", new[] { "stationary", "part_time" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shogun.Schedule.Domain.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("faculties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("31e7c100-9d3f-4eb1-a388-c38f36b999a1"),
                            Code = "WI",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Informatyka"
                        },
                        new
                        {
                            Id = new Guid("63c16df1-c743-41e0-b6da-8c67b19d5b1e"),
                            Code = "SNM",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sztuka Nowych Mediów"
                        });
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AuthorUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleEntryId", "CreatedAt");

                    b.ToTable("schedule_comments", (string)null);
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClassType")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LecturerDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LecturerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("LecturerUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Room")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubjectExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SubjectSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "LecturerUserId");

                    b.HasIndex("ScheduleId", "DayOfWeek", "StartMinute");

                    b.ToTable("schedule_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_entries_day", "\"DayOfWeek\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_entries_time", "\"StartMinute\" >= 480 AND \"StartMinute\" + \"DurationMinutes\" <= 1200 AND \"StartMinute\" % 15 = 0 AND \"DurationMinutes\" > 0 AND \"DurationMinutes\" % 15 = 0");
                        });
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleEntryGroup", b =>
                {
                    b.Property<Guid>("ScheduleEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleEntryId", "StudentGroupId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("schedule_entry_groups", (string)null);
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.SchedulePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudyMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId", "AcademicYear", "SemesterNumber", "StudyMode")
                        .IsUnique();

                    b.ToTable("schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_schedules_semester", "\"SemesterNumber\" BETWEEN 1 AND 8");

                            t.HasCheckConstraint("ck_schedules_year", "\"AcademicYear\" ~ '^[0-9]{4}/[0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "Code")
                        .IsUnique();

                    b.HasIndex("ScheduleId", "SortOrder")
                        .IsUnique();

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleComment", b =>
                {
                    b.HasOne("Shogun.Schedule.Domain.ScheduleEntry", "ScheduleEntry")
                        .WithMany("Comments")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleEntry", b =>
                {
                    b.HasOne("Shogun.Schedule.Domain.SchedulePlan", "Schedule")
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleEntryGroup", b =>
                {
                    b.HasOne("Shogun.Schedule.Domain.ScheduleEntry", "ScheduleEntry")
                        .WithMany("EntryGroups")
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shogun.Schedule.Domain.StudentGroup", "StudentGroup")
                        .WithMany("EntryGroups")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntry");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.SchedulePlan", b =>
                {
                    b.HasOne("Shogun.Schedule.Domain.Faculty", "Faculty")
                        .WithMany("Schedules")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.StudentGroup", b =>
                {
                    b.HasOne("Shogun.Schedule.Domain.SchedulePlan", "Schedule")
                        .WithMany("Groups")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.Faculty", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.ScheduleEntry", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EntryGroups");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.SchedulePlan", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Shogun.Schedule.Domain.StudentGroup", b =>
                {
                    b.Navigation("EntryGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
